/*
 * Homework Problem 3.60 from CS:APP: Consider the following assembly code:
 *
 *     # long loop(long x, int n)
 *     # x in %rdi, n in %esi
 *     loop:
 *       movl	%esi, %ecx
 *       movl	$1, %edx
 *       movl	$0, %eax
 *       jmp	.L2
 *     .L3:
 *       movq	%rdi, %r8
 *       andq	%rdx, %r8
 *       orq	%r8, %rax
 *       salq	%cl, %rdx
 *     .L2:
 *       testq	%rdx, %rdx
 *       jne	.L3
 *       rep; ret
 *
 * The preceding code was generated by compiling C code that had the following
 * overall form:
 *
 *     long loop(long x, long n)
 *     {
 *         long result = ____
 *         long mask;
 *         for (mask = ____; mask ____; mask = ____) {
 *             result |= ____;
 *         }
 *         return result;
 *     }
 *
 * Your task is to fill in the missing parts of the C code to get a problem
 * equivalent to the generated assembly code. Recall that the result of the
 * function is returned in register %rax. You will find it helpful to examine
 * the assembly code before, during, and after the loop to form a consistent
 * mapping between the registers and the program variables.
 *
 * A. Which registers hold program values x, n, result, and mask?
 *
 *     x is in %rdi, n is in %esi, result is in %rax, and mask is in %rdx.
 *
 * B. What are the initial values of result and mask?
 *
 *    result is 0 and mask is 1 initially.
 *
 * C. What is the test condition for mask?
 *
 *     mask != 0
 *
 * D. How does mask get updated?
 *
 *     mask <<= n
 *
 * E. How does result get updated?
 *
 *     result |= x & mask
 *
 * F. Fill in all the missing parts of the C code.
 */

long loop(long x, long n)
{
	long result = 0;
	long mask;
	for (mask = 1; mask != 0; mask = mask << n) {
		result |= (x & mask);
	}
	return result;
}

int main(void)
{
	long r = loop(1234567890, 4);
}
