/*
 * Homework Problem 3.67 from CS:APP: For this exercise, we will examine the
 * code generated by GCC for functions that have structures as arguments and
 * return values, and from this see how these language features are typically
 * implemented.
 * The following C code has a function process having structures as argument
 * and return values, and a function eval that calls process:
 *
 *     typedef struct {
 *         long a[2];
 *         long *p;
 *     } strA;
 *
 *     typedef struct {
 *         long u[2];
 *         long q;
 *     } strB;
 *
 *     strB process(strA s) {
 *         strB r;
 *         r.u[0] = s.a[1];
 *         r.u[1] = s.a[0];
 *         r.q =    *s.p;
 *         return r;
 *     }
 *
 *     long eval(long x, long y, long z) {
 *         strA s;
 *         s.a[0] = x;
 *         s.a[1] = y;
 *         s.p = &z;
 *         strB r = process(s);
 *         return r.u[0] + r.u[1] + r.q;
 *     }
 *
 * GCC generates the following code for these two functions:
 *
 *     strB process(strA s)
 *     process:
 *       movq      %rdi, %rax
 *       movq      24(%rsp), %rdx
 *       movq      (%rdx), %rdx
 *       movq      16(%rsp), %rcx
 *       movq      %rcx, (%rdi)
 *       movq      8(%rsp), %rcx
 *       movq      %rcx, 8(%rdi)
 *       movq      %rdx, 16(%rdi)
 *       ret
 *
 *     long eval(long x, long y, long z)
 *     x in %rdi, y in %rsi, z in %rdx
 *     eval:
 *       subq      $104, %rsp
 *       movq      %rdx, 24(%rsp)
 *       leaq      24(%rsp), %rax
 *       movq      %rdi, (%rsp)
 *       movq      %rsi, 8(%rsp)
 *       movq      %rax, 16(%rsp)
 *       leaq      64(%rsp), %rdi
 *       call      process
 *       movq      72(%rsp), %rax
 *       addq      64(%rsp), %rax
 *       addq      80(%rsp), %rax
 *       addq      $104, %rsp
 *       ret
 *
 * A. We can see on line 2 of functions eval that it allocates 104 bytes on the
 *    stack. Diagram the stack frame for eval, showing the values that it stores
 *    on the stack prior to calling process.
 *
 *    Prior to calling process, eval stores the following values on the stack: 
 *        - x at %rsp (s.a[0])
 *        - y at %rsp + 8 (s.a[1])
 *        - &z at %rsp + 16 (s.p)
 *        - z at %rsp + 24 (*s.p)
 *
 * B. What value does eval pass in its call to process?
 *
 *    eval passes a pointer in %rdi to the location on the stack where process
 *    will place the struct r.
 *
 * C. How does the code for process access the elements of structure argument s?
 *
 *    process accesses the elements of s by their offsets from the stack pointer:
 *        - s.a[0] at %rsp + 8
 *        - s.a[1] at %rsp + 16
 *        - s.p at %rsp + 24
 *
 * D. How does the code for process set the fields of result structure r?
 *
 *        - r.u[0] = s.a[1] is done with two moves:
 *          movq 16(%rsp), %rcx   s.a[1] -> %rcx
 *          movq %rcx, (%rdi)     %rcx -> r.u[0]
 *        - r.u[1] = s.a[0] is done with two moves:
 *          movq 8(%rsp), %rcx    s.a[0] -> %rcx
 *          movq %rcx, 8(%rdi)    %rcx -> r.u[1]
 *        - r.q = *s.p is done with three moves:
 *          movq 24(%rsp), %rdx   s.p -> %rdx
 *          movq (%rdx), %rdx     *s.p -> %rdx
 *          movq %rdx, 16(%rdi)   *s.p -> r.q
 *
 * E. Complete your diagram of the stack frame eval, showing how eval accesses
 *    the elements of structure r following the return from process.
 *
 *    eval accesses the elements of structure r using offsets from %rsp + 64
 *    after process returns:
 *        - r.u[0] at %rsp + 64
 *        - r.u[1] at %rsp + 72
 *        - r.q at %rsp + 80
 *
 * F. What general principles can you discern about how structure values are
 *    passed as function arguments and how they are returned as function results?
 *
 *    A calling function can allocate enough space in its stack frame so that it
 *    can both pass a struct to and receive a struct from a function whose
 *    values are located on the stack.
 */
